sonar.projectKey=Eniyonta_aws-devops-ci-cd-project
sonar.organization=eniyonta
sonar.projectName=Flask DevSecOps App
sonar.projectVersion=1.0
sonar.sources=app
sonar.language=py
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
